# Generated by Django 5.2 on 2025-05-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_taskchangelog_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Nowy', 'Nowy'), ('W_toku', 'W_toku'), ('Rozwiązany', 'Rozwiązany')], default='new', max_length=50),
        ),
    ]
